title: Lara Thompson
name: Lara Thompson
description: Yet another physicist doing ML.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://lrthomps.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: lrthomps/lrthomps.github.io

github_username:  lrthomps

markdown: kramdown
kramdown:
  math_engine: nil

author:
  name             : "Lara Thompson"
  avatar           : "/assets/images/avatar.jpg"

# Build settings
plugins:
  - jekyll-feed
permalink: /posts/:title.html


exclude:
  - Gemfile
  - Gemfile.lock
