---
title:  "References for Data, ML, Math etc."
categories: ["machine learning"]
date:   "2019-09-19"
description: Some dated and more or less relevant references to get started in ML. 
page-layout: full
title-block-banner: true

---

Excellent posts:

* <a href="https://developers.google.com/machine-learning/guides/rules-of-ml/">Rules of ML</a> from Google
* <a href="https://karpathy.github.io/2019/04/25/recipe/">A Recipe for Training Neural Networks</a> by Andrej Karpathy


I learn best from reading, not coursera-like videos (though who didn’t enjoy Andrew Ng’s course?). Papers are important to keep up with the latest, but to fill in the background usually left unexplained and to expose the bits I never knew I didn’t know: I turn to textbooks. 

Starting out, I read a bunch of textbooks and as far as I know these are still good starting points:

* <a href="http://neuralnetworksanddeeplearning.com/">Neural Networks and Deep Learning</a> by Michael Nielsen: back prop, loss functions, problems when neural networks go deep

* <a href="https://www.deeplearning.ai/machine-learning-yearning/">Machine Learning Yearning</a> by Andrew Ng: how to train a model and ensure it works in the real world

* <a href="https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/">Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow</a> by Aurélien Géron: it’s all in the title, great book


On more specific topics, I can recommend:

* <a href="https://christophm.github.io/interpretable-ml-book/">Interpretable Machine Learning</a> by Christoph Molnar: discusses the inherently explainable models and how to interpret black-box models.

* <a href="https://www.andrew.cmu.edu/course/10-703/textbook/BartoSutton.pdf">Reinforcement Learning</a> by Sutton and Barto: a slow building up of concepts to some of the most powerful RL algorithms and the language to understand the latest research.

* <a href="https://www.oreilly.com/library/view/designing-data-intensive-applications/9781491903063/">Designing Data-Intensive Applications</a> by Martin Kleppman: brilliant book not specifically about data science. Read this to understand the difficulties navigating big data.

* <a href="https://www.goodreads.com/book/show/12818088-mining-of-massive-datasets">Mining of Massive Datasets</a> by Rajaraman and Ullman: a surprising deep and thorough book on scaling algorithms to big data, covering map-reduce, stream processing, PageRank and recommenders at scale.

Beyond purely technical topics, I also suggest:

* <em>UX for beginners</em> as a quick intro to an important role in product development that (can) interact with data scientists
* <em>Weapons of Math Destruction</em> on the damage of unacknowledged bias in models
* <em>Gödel’s Proof</em> because it’s linked to the “No free lunch” theorem and generally mind-blowing


